name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  flutter_gradient_colors: ^2.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  cloud_functions: ^4.7.6
  intl: ^0.19.0
  table_calendar: ^3.1.2
  introduction_screen: ^3.1.14
  shared_preferences: ^2.0.11
  loading_animation_widget: ^1.2.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1+2
  http: ^1.1.0  # Added HTTP package
  pay: ^2.0.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/illustrations/
