name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  flutter_gradient_colors: ^2.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cloud_functions: ^4.5.8
  intl: ^0.19.0
  table_calendar: ^3.0.9
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^18.0.1
  http: ^1.1.2
  pay: ^1.1.2
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  timezone: ^0.9.2
  flutter_stripe: ^10.0.0
  firebase_app_check: ^0.2.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/illustrations/